### ISSUE TITLE
OAM - Update Browser Banner

### ISSUE THREAD

**Issue by JMurk** [JMurk/DPW_and_CW_Activity_Applications#1]
Please update the browser banner to read "OAM Activity Manager."  Also, please add an .ico file to the title html.

![image](https://cloud.githubusercontent.com/assets/5805454/4152992/e0ad6972-3453-11e4-84a4-911c0ef8577c.png)

**Comment by kanglu666** [comment]
updated at city dev

**Comment by JMurk** [comment]
Confirmed complete.
