### ISSUE TITLE
OAM - SSO Investigation Details - Dropdowns

### ISSUE THREAD

**Issue by JMurk** [JMurk/DPW_and_CW_Activity_Applications#10]
Issue:  Fields with dropdowns allow users to type in and save values not in the list.

![image](https://cloud.githubusercontent.com/assets/5805454/4153952/9f0e3078-345d-11e4-8178-45efdf1a7d7e.png)

Resolution:  Please do not allow users to manually type inside of dropdown-controlled boxes.

**Comment by kanglu666** [comment]
done

**Comment by JMurk** [comment]
Confirmed complete.
