### ISSUE TITLE
Cityworks Activity Browser - Description Validation

### ISSUE THREAD

**Issue by JMurk** [JMurk/DPW_and_CW_Activity_Applications#100]
**Issue:** The description field does not seem to be validating properly.  I passed in a value of "Test" and it claimed it was valid.

![image](https://cloud.githubusercontent.com/assets/5805454/9858295/e1017532-5aed-11e5-9c62-148926164c5a.png)

**Comment by JMurk** [comment]
Update:  It did not import
![image](https://cloud.githubusercontent.com/assets/5805454/9858581/81b66eb4-5aef-11e5-80cb-0681df3dcfbd.png)

**Comment by jday3** [comment]
"TEST" is a valid description (according to the database). The reason it did not import is because the Description/Entity combination does not exist as a template (if you hover over the icon next to the row is should show the issue)

**Comment by JMurk** [comment]
This check should be a part of the verification.  If the description does not match, they verify still succeeds.  I should fail, saying that errors exist.

**Comment by jday3** [comment]
description/entity must match like we discussed earlier

**Comment by JMurk** [comment]
Confirmed complete.
