### ISSUE TITLE
Cityworks Activity Browser - Import - Add Rows

### ISSUE THREAD

**Issue by JMurk** [JMurk/DPW_and_CW_Activity_Applications#101]
Is it possible to have functionality built in that allows users to add new rows to the grid?  Perhaps something like this:

![image](https://cloud.githubusercontent.com/assets/5805454/9858510/254a2b8e-5aef-11e5-8533-5e9e481029d4.png)

**Comment by jday3** [comment]
done

**Comment by JMurk** [comment]
This looks good, however, when you click "Add New" the system immediately gives you the Invalid Records error message.  It seems like it is trying to validate the new record before the user is able to enter anything.
![image](https://cloud.githubusercontent.com/assets/5805454/9905245/d6191cc8-5c51-11e5-95c4-db6c61d0ab7a.png)

**Comment by jday3** [comment]
done on test

**Comment by JMurk** [comment]
Complete.
