### ISSUE TITLE
Cityworks Activity Browser - Import - Filter Description Dropdown

### ISSUE THREAD

**Issue by JMurk** [JMurk/DPW_and_CW_Activity_Applications#102]
Is it possible to filter the Description drop down based on what Entity is populated?  If there is no entity, or the entity is invalid, it would just display all options.

![image](https://cloud.githubusercontent.com/assets/5805454/9858993/f3aefd7c-5af1-11e5-8f94-88309a3277c0.png)

**Comment by jday3** [comment]
Sure, it is possible. Would the description become invalid if the entity is updated and the current value of description is filtered out?

**Comment by JMurk** [comment]
Yes, it should.  Lets put this in place.

**Comment by jday3** [comment]
done

**Comment by JMurk** [comment]
Confirmed complete.
