### ISSUE TITLE
Cityworks Activity Browser - Batch Load - Add Fields

### ISSUE THREAD

**Issue by JMurk** [JMurk/DPW_and_CW_Activity_Applications#103]
Please add the following fields to the batch import functionality.  They will need to be added to the app and the Excel template:

-Project (PROJECTNAME) -validate using list of projects via API.  Otherwise use the PROJECT table.
-Contract (CONTRACTWOID ?)  -validate using list of contracts via API.  Otherwise use the CONTRACT table
-Supervisor (SUPERVISOR) - validate like requested by
-Status (STATUS) - validate using API.

As for placement, put project and contract before comments. Supervisor can go after Priority. Status can go after description

**Comment by jday3** [comment]
done on test

**Comment by JMurk** [comment]
I uploaded a spreadsheet that had all invalid Contracts. There was noting on the UI, besides a tool tip that indicated that field was the issue.  Can we highlight the invalid cells or something?

Also, can you please use Contract Number instead of description for validation?

**Comment by jday3** [comment]
done

**Comment by jday3** [comment]
Now the contract name is being used to display

**Comment by JMurk** [comment]
Now I am getting an error:

![image](https://cloud.githubusercontent.com/assets/5805454/11628643/f7cd2d5a-9cc0-11e5-9661-7c947846e691.png)

**Comment by jday3** [comment]
Update - The importing is now working, but I am running into an issue where the requests are timing out after two minutes. All of the workorders are being uploaded correctly, but the response to the browser is invalid. You can test with a smaller batch for the time being if you wish

**Comment by jday3** [comment]
okay, now it should be working.

**Comment by JMurk** [comment]
As discussed, please check for the # sign being a special character in the comments.  Also, records without Asset IDs failed to import.  Can you check to see if they are mistakenly required on the backend?

**Comment by jday3** [comment]
Both should be fixed

**Comment by JMurk** [comment]
Ok, everything looks like it is good to go.  Please push all development changes to production.

**Comment by taojun545** [comment]
Joe talked with me this morning, and I will push all development changes to production. Since I am not in the Assignee list, could anyone assign this issue to me?

**Comment by taojun545** [comment]
Updated on Production.

**Comment by JMurk** [comment]
A few changes:
1. It appears as the API is using my credentials.  Can you change so that it uses:

API /API123
1. Can you further filter the dropdown in the Project column using "Where DomainID = 3"

**Comment by taojun545** [comment]
Updated on dev.

For Project Combo, add more filter as
Where(t => t.DOMAINID == 3 && t.CANCEL.Equals("N") && !String.IsNullOrEmpty(t.PROJECTNAME))

**Comment by JMurk** [comment]
Since this update, everything is very buggy.  For example, the verify button is non-functional and once you edit one field, all others become uneditable. Please investigate this.

**Comment by JMurk** [comment]
We also need to filter the Status dropdown where values not in ('CLOSED', 'COMPLETE', CM COMPLETE', 'CLOSED/INCOMPLETE')

**Comment by taojun545** [comment]
Fixed the bug and updated Status dropdown on dev.

**Comment by taojun545** [comment]
Fixed the bug to handle empty "Comments" and skip "/AMS/WorkOrder/AddEntities" if no AssetID uploaded. The updates were on dev. 

@JMurk need to check WOTEMPLATE table in DPW_Cityworks. Entity dropdown options are from APPLYTOENTITY in that table, which include inactive entities.

**Comment by JMurk** [comment]
It appears the Status dropdown is yielding no values and causing the imported records to be invalid and not uploadable.  Please check how the Status values is being pulled from the API or database.

**Comment by taojun545** [comment]
The status value is from "/AMS/WorkOrder/Statuses", which gets a list of available work order statuses

**Comment by JMurk** [comment]
Confirmed complete, please push to production.

**Comment by taojun545** [comment]
Updated all followings on production.
- change credential to "API/API123"
- Filter Project dropdown using "DomainID = 3"
- Filter Status dropdown not include ('CLOSED', 'COMPLETE', CM COMPLETE', 'CLOSED/INCOMPLETE')
- Fixed the bugs to handle empty "Address", empty "Comments", require "Requested By" and skip "/AMS/WorkOrder/AddEntities" if no AssetID uploaded

**Comment by JMurk** [comment]
Confirmed complete.
