### ISSUE TITLE
OAM - SSO Investigation - Follow-up Status Typo

### ISSUE THREAD

**Issue by JMurk** [JMurk/DPW_and_CW_Activity_Applications#104]
On the investigation form within the SSO Investigation activity, the Follow-up Status dropdown includes a value with a typo.  

"Comfirmed" should be "Confirmed"

![image](https://cloud.githubusercontent.com/assets/5805454/11732879/9fa49664-9f76-11e5-9eac-bfbea365d388.png)

**Comment by taojun545** [comment]
Updated on dev.

**Comment by JMurk** [comment]
Confirmed complete, ready for prod.

**Comment by taojun545** [comment]
Updated on production. The combo is dynamically using domain list now.

**Comment by JMurk** [comment]
Confirmed complete.
