### ISSUE TITLE
OAM - SSO Investigation - Recommendation Responsibility - UAMD

### ISSUE THREAD

**Issue by JMurk** [JMurk/DPW_and_CW_Activity_Applications#105]
Please update the value "UAMD" to "OAM".  Also, is is possible to check for the value "UAMD" throughout the application?  If so, any remaining values should be updated to "OAM"

![image](https://cloud.githubusercontent.com/assets/5805454/11733318/4360fea2-9f7a-11e5-8ea2-0dc2c82fee4e.png)

**Comment by taojun545** [comment]
Updated followings on dev.
- Recommendation Responsibility Dropdown
- Layer Name on SSO & CCTV

**Comment by JMurk** [comment]
Confirmed complete... Are those dropdowns hard-coded?

**Comment by taojun545** [comment]
Yes. Most of the dropdowns in SSO are hard-coded.

**Comment by JMurk** [comment]
We should update to use the domain values.  Is that a large effort?  If so we can push this change and I will open another issue for that update.

**Comment by taojun545** [comment]
It will be a lot of changes. Please open another issue for it.

**Comment by taojun545** [comment]
All the hard-coded dropdowns in SSO have been updated into dynamic dropdowns on dev.

**Comment by JMurk** [comment]
Confirmed complete.
