### ISSUE TITLE
OAM - Create New Investigation - Enforce Selection of SSO

### ISSUE THREAD

**Issue by JMurk** [JMurk/DPW_and_CW_Activity_Applications#106]
**Issue:**  In the SSO Investigation Activity, the create new investigation button allows users to create a new investigation without selecting an SSO from the grid.

![image](https://cloud.githubusercontent.com/assets/5805454/11785148/47c7da34-a24e-11e5-9bb5-01277026e9c2.png)

**Resolution:** On click, check to see if an SSO had been selected.  If not, prompt a warning message that states "Please select an SSO to investigate!"

AND/OR

Disable to button until at least one is selected.

**Comment by taojun545** [comment]
Updated on dev. When click, check to see if an SSO had been selected. If not, prompt a warning message that states "Please select an SSO to investigate!"

**Comment by JMurk** [comment]
When you click the Add to Existing Investigation button without SSOs selected, it correctly prompts a message, however it is a browser warning.  Can you update that to be the application pop-up style.  It should read:

"Please select SSOs to be added!"

![image](https://cloud.githubusercontent.com/assets/5805454/14676950/90571cbc-06dd-11e6-8c25-764e5e828172.png)

**Comment by taojun545** [comment]
Updated on dev.

**Comment by JMurk** [comment]
Confirmed complete, ready for push to prod.

**Comment by taojun545** [comment]
Updated on production.

**Comment by JMurk** [comment]
Confirmed complete.
