### ISSUE TITLE
OAM - SSOs without an Investigation - Add Overflow Type Column

### ISSUE THREAD

**Issue by JMurk** [JMurk/DPW_and_CW_Activity_Applications#107]
Please add a column to the "SSOs without an Investigation" called "Overflow Type" (this exists in the Recent SSOs with an Investigation grid).  It can be placed to the right of Choke Type.

![image](https://cloud.githubusercontent.com/assets/5805454/11785407/b655d798-a24f-11e5-9a5c-9272bab8d571.png)

**Comment by taojun545** [comment]
Updated on dev.

**Comment by JMurk** [comment]
Confirmed complete, ready for push to prod.

**Comment by taojun545** [comment]
Updated on production.

**Comment by JMurk** [comment]
Confirmed complete.
