### ISSUE TITLE
OAM - Google Street View 

### ISSUE THREAD

**Issue by JMurk** [JMurk/DPW_and_CW_Activity_Applications#108]
**Issue:** The Google street view tool is not working.  It just displays blank.

![image](https://cloud.githubusercontent.com/assets/5805454/11785698/fd708398-a250-11e5-83f8-fec83b6509e8.png)

**Resolution:** Please investigate and resolve accordingly.

**Comment by taojun545** [comment]
Updated on dev.

**Comment by taojun545** [comment]
It was using "http://mdimap.towson.edu/ArcGIS/rest/services/GeometryService/Geometry/GeometryServer", and I updated with "http://10.1.65.43:6080/arcgis/rest/services/Utilities/Geometry/GeometryServer"

**Comment by JMurk** [comment]
Confirmed complete, ready for push to prod.

**Comment by taojun545** [comment]
Updated on production.

**Comment by JMurk** [comment]
Confirmed complete.
