### ISSUE TITLE
OAM - SSO Recommendations - Make By and Date Uneditable

### ISSUE THREAD

**Issue by JMurk** [JMurk/DPW_and_CW_Activity_Applications#109]
**Issue:**  For Recommendations, the Recommendation Date and Recommended By fields are correctly autopopulated on creation.  These value are then editable, which is not correct.  

![image](https://cloud.githubusercontent.com/assets/5805454/11786085/b542d3f8-a252-11e5-8b6c-774a592fef1f.png)

**Resolution:** Please set Recommendation Date and Recommended By to be read-only on the UI.

**Comment by taojun545** [comment]
Updated on dev.

**Comment by JMurk** [comment]
Confirmed complete, ready for push to prod.

**Comment by taojun545** [comment]
Updated on production.

**Comment by JMurk** [comment]
Confirmed complete.
