### ISSUE TITLE
OAM - SSO Investigation Existing Details - Comments Column

### ISSUE THREAD

**Issue by JMurk** [JMurk/DPW_and_CW_Activity_Applications#11]
Issue:  When the details are longer then the width of the "Comments" column in the Existing Details grid, you cannot see the entire comment.

![image](https://cloud.githubusercontent.com/assets/5805454/4154107/e495c2f4-345e-11e4-8f9b-4acb2aa248f6.png)

Resolution:  The entire comment should be viewable in the grid, not matter its length.

**Comment by kanglu666** [comment]
updated

**Comment by JMurk** [comment]
Confirmed complete.
