### ISSUE TITLE
SSO Activity Manager - Identify Results change

### ISSUE THREAD

**Issue by alanfoster99** [JMurk/DPW_and_CW_Activity_Applications#113]
Can the identify results of investigated SSOs be changed so that instead of returning the full results of the SSO point, the user can link from the Identify Results directly to the "Updated Investigation" page via single click?  This page holds the info they need for analyzing results.  See below:

![image](https://cloud.githubusercontent.com/assets/7118831/14251909/0fe54d1a-fa53-11e5-88fa-2ecd93fbf90b.png)

Instead of expanding to show SSO results, please link to "Go To Investigation" as is possible on the intro page:

![image](https://cloud.githubusercontent.com/assets/7118831/14251936/272a8b66-fa53-11e5-8310-d92cc55a0325.png)

**Comment by JMurk** [comment]
I think this is possible in one way or another.  I will need to review with developers to determine the best approach.

**Comment by JMurk** [comment]
After talking with Jun, we can add a right-click menu item for "Open Investigation."  Will that work?

![image](https://cloud.githubusercontent.com/assets/5805454/14708416/c7579aa0-0798-11e6-96ad-1555a2fac4cf.png)

**Comment by alanfoster99** [comment]
Yeah, sounds good

**Comment by taojun545** [comment]
Updated on dev.

**Comment by JMurk** [comment]
Confirmed complete in dev, ready for prod.

**Comment by taojun545** [comment]
Updated on production.

**Comment by JMurk** [comment]
Confirmed complete.
