### ISSUE TITLE
CW Activity - New fields for Batch Work Order Create tool

### ISSUE THREAD

**Issue by alanfoster99** [JMurk/DPW_and_CW_Activity_Applications#115]
Please add the following fields to the batch load tool (_none are required_)

**Resolution:**
[RESOLUTION]
Invalid Work Order/Error
No Problem Found
Other (Explain in Comments)
Work Performed

**Initiate Date**
[INITIATEDATE]
_date:_ mm/dd/yyyy hh:mm: AM/PM

**Actual Finish Date**
[ACTUALFINISHDATE]
_date:_ mm/dd/yyyy hh:mm: AM/PM

**Cycle Frequency**
[CYCLEINTERVALNUM]
_(Integer)_

**Cycle Interval Unit**
[CYCLEINTERVALUNIT]
D
M
W
Y

**Cycle assignment type**
[CYCLETYPE]
A
B
C

**Comment by taojun545** [comment]
Updated on the DEV. Please go ahead to test it.

**Comment by alanfoster99** [comment]
Please add one more field for "CYCLE FROM"; acceptable values are:

"actual finish date" / "projected start date" / "pick a date"

**Comment by taojun545** [comment]
If the CycleFrom value is "Pick a Date", it should upload another field "FromDate".

@alanfoster99 So do we need to add one more field?

**Comment by taojun545** [comment]
For now, we will implement the acceptable values of "CYCLE FROM" only have:
"actual finish date" / "projected start date"

**Comment by taojun545** [comment]
Updated on DEV.

**Comment by alanfoster99** [comment]
Verified.  Please push to production.

**Comment by taojun545** [comment]
Updated on production.

**Comment by alanfoster99** [comment]
Confirmed and closing
