### ISSUE TITLE
CW Activity - Batch load issue with Priority

### ISSUE THREAD

**Issue by alanfoster99** [JMurk/DPW_and_CW_Activity_Applications#116]
When loading records via batch tool, those with "MEDIUM" get mapped to MEDIUM HIGH.  Please correct this so they are mapped to MEDIUM.

**Comment by taojun545** [comment]
The current mapping code is finding the first matching option with the same beginning, and "Medium High" is before "Medium". I will correct the code to find the exact match.

**Comment by taojun545** [comment]
Fixed the bug on DEV.

**Comment by alanfoster99** [comment]
Verified.  Please push to production

**Comment by taojun545** [comment]
Updated on production.

**Comment by alanfoster99** [comment]
Verified and closing
