### ISSUE TITLE
OAM - SSO Investigation

### ISSUE THREAD

**Issue by alanfoster99** [JMurk/DPW_and_CW_Activity_Applications#117]
Please add amended reports to the Activity Manager – currently only links to 24 hr and 5 day … does not show amended.

For example:

http://dpwview.baltimorecity.gov/SSOReport/SSOReport5DAYamended.aspx?SSOID=3892

**Comment by taojun545** [comment]
Updated on DEV.

**Comment by alanfoster99** [comment]
Please add a Boolean test; if Amended = No in the SSO table, then do not show link for 5 day amended.

**Comment by taojun545** [comment]
Updated on DEV. Show the link if Amended is true, otherwise hide it.

**Comment by alanfoster99** [comment]
Looks good -- please push to PROD.

**Comment by taojun545** [comment]
Updated on PROD.

**Comment by alanfoster99** [comment]
Confirmed and closing.  Thanks.
