### ISSUE TITLE
OAM - Recommedation - Priority Dropdown

### ISSUE THREAD

**Issue by JMurk** [JMurk/DPW_and_CW_Activity_Applications#12]
Issue:  The priority dropdown only has a value of "Delete", which is not valid.

![image](https://cloud.githubusercontent.com/assets/5805454/4154377/295a33fa-3461-11e4-8f84-04e8d2f385ec.png)

Resolution: Please update the valid values to include:

-High
-Medium
-Low

**Comment by kanglu666** [comment]
done

**Comment by JMurk** [comment]
Confirmed complete.
