### ISSUE TITLE
OAM - SSO Investigation - Save Confirmation Message

### ISSUE THREAD

**Issue by JMurk** [JMurk/DPW_and_CW_Activity_Applications#14]
Please change the following conformation message:

![image](https://cloud.githubusercontent.com/assets/5805454/4154736/5d370bbe-3464-11e4-9a46-cfb5ea872f75.png)

to read:
"The Investigation has been saved successfully!"

**Comment by kanglu666** [comment]
done

**Comment by JMurk** [comment]
Confirmed complete.
