### ISSUE TITLE
OAM - SSO Investigation - Other Cause Require Description

### ISSUE THREAD

**Issue by JMurk** [JMurk/DPW_and_CW_Activity_Applications#15]
When Other is checked as a cause, please make the Other description field required.

![image](https://cloud.githubusercontent.com/assets/5805454/4154773/a0fdeea8-3464-11e4-823e-0ca208f8553c.png)

**Comment by kanglu666** [comment]
done

**Comment by JMurk** [comment]
Confirmed complete.
