### ISSUE TITLE
OAM - SSO Investigation - Most Recent Occurrence

### ISSUE THREAD

**Issue by JMurk** [JMurk/DPW_and_CW_Activity_Applications#16]
For the Most Recent Occurrence field, the following issues exist:
1. Fix the spelling of the label to "Occurrence"
2. It is not auto populating using the MAX Occurrence date of related SSOs.

![image](https://cloud.githubusercontent.com/assets/5805454/4155868/9d8a3128-346e-11e4-830f-0f9c043b3865.png)

**Comment by kanglu666** [comment]
done

**Comment by JMurk** [comment]
Spelling has been fixed, but is still not updating when a new SSO is added to an existing investigation.

**Comment by kanglu666** [comment]
updated

**Comment by JMurk** [comment]
Confirmed complete.
