### ISSUE TITLE
OAM - Type Ahead in Activity Dropdown

### ISSUE THREAD

**Issue by JMurk** [JMurk/DPW_and_CW_Activity_Applications#17]
**Issue**:  The application allows the user to type in the Activity dropdown.  This should not be allowed as they need to pick an option from the list.
![image](https://cloud.githubusercontent.com/assets/5805454/4235206/97f918b0-39bd-11e4-88f6-9baea7afb311.png)

**Resolution**: Disable typing in the Activity input box.

**Comment by kanglu666** [comment]
updated

**Comment by JMurk** [comment]
Confirmed complete.
