### ISSUE TITLE
OAM - Domained Fields

### ISSUE THREAD

**Issue by JMurk** [JMurk/DPW_and_CW_Activity_Applications#18]
The application needs to be able to read from and write coded values to the database.  I will send the data dictionary for the SSO investigation & Recommedation portion.  Please be sure that all values from the spreadsheet match in the application.

**Comment by kanglu666** [comment]
All Domains in SSO investigation & Recommedation form have been applied.

**Comment by JMurk** [comment]
For CCTV Status, the code for Available has a space at the end.  Please remove the space.  

![image](https://cloud.githubusercontent.com/assets/5805454/4345484/b264d40e-40d0-11e4-8cbc-49bafdab962a.png)

**Comment by kanglu666** [comment]
updated

**Comment by JMurk** [comment]
Confirmed complete.
