### ISSUE TITLE
OAM - Add Map Layers

### ISSUE THREAD

**Issue by JMurk** [JMurk/DPW_and_CW_Activity_Applications#19]
Please add the map services that I had mentioned in an e-mail previously.

•         Sewer Work Orders
•         Sewer CSRs
•         UAMD Wastewater
•         Water
•         Wastewater
•         County Wastewater
•         Stormwater
•         Index
•         Consent Decree
•         Geo Technical
•         Topo
•         Utility Boundaries
•         FSE
•         Orthos

**Comment by kanglu666** [comment]
all map services except the CSRs (not working in dev) have been added into the app

**Comment by JMurk** [comment]
Looks good, but can you move Topo above BaseMap?  I will look into CSR issue.

**Comment by kanglu666** [comment]
done

**Comment by JMurk** [comment]
It looks like the map layer display properly on the map, but the TOC doesn't have them in visibility order.  Make sure the TOC is in visibility order and make sure the order is as follows (**Bold** layers should be on by default):
•         Sewer Work Orders
•         Sewer CSRs
**•        SSO**
•        FSE
•        UAMD Wastewater
•         Water
**•         Wastewater**
•         County Wastewater
•         Stormwater
•         Index
•         Consent Decree
•         Geo Technical
•         Topo
•         Utility Boundaries
**•         BaseMap**
•         Orthos

**Comment by JMurk** [comment]
Also, be sure to add UAMD Wastewater .... The map service name for that feed is UAMD.

**Comment by kanglu666** [comment]
updated

**Comment by JMurk** [comment]
Confirmed complete.
