### ISSUE TITLE
OAM - Change URL for City App

### ISSUE THREAD

**Issue by JMurk** [JMurk/DPW_and_CW_Activity_Applications#2]
Issue:  Currently, the app has a URL with the ending of /ssoinvestigatewebapi/index.html.  This will include much more then just SSO investigations.

Resolution:  Please update to something along the lines of /ActivityManager/index.html

**Comment by kanglu666** [comment]
URL has been updated:
http://dpwdev.baltimorecity.gov/water/ActivityManager/index.html

**Comment by JMurk** [comment]
Confirmed complete.
