### ISSUE TITLE
OAM - Identify Function

### ISSUE THREAD

**Issue by JMurk** [JMurk/DPW_and_CW_Activity_Applications#20]
Please add the identify function to the map portion of the application.  Results should populate in a horizontal grid under "Query Results"

**Comment by kanglu666** [comment]
what layer users need to identify? what's the workflow?

**Comment by JMurk** [comment]
All visible layers not in the BaseMap.  

**Workflow**:  Click identify button, select features by drawing a box.

**Comment by kanglu666** [comment]
Identify Function has been added in OAM app, please test

**Comment by JMurk** [comment]
Confirmed complete.
