### ISSUE TITLE
OAM - Workspace Cut Off on Small Screens

### ISSUE THREAD

**Issue by JMurk** [JMurk/DPW_and_CW_Activity_Applications#23]
**Issue**:  On smaller screens, some things get cut off and the user has no way to access them.

![image](https://cloud.githubusercontent.com/assets/5805454/4250126/1c3720aa-3a80-11e4-84f8-afffc72a73ca.png)

**Resolution**: Please add a horizontal scroll bar, or another way access all parts of that panel on all size screens.

**Comment by kanglu666** [comment]
scroll bar added

**Comment by JMurk** [comment]
Confirmed complete.
