### ISSUE TITLE
OAM - Total SSO Label

### ISSUE THREAD

**Issue by JMurk** [JMurk/DPW_and_CW_Activity_Applications#24]
**Issue**:  On the SSO tab of an investigation, the total SSOs box is labeled as "Total Account"

![image](https://cloud.githubusercontent.com/assets/5805454/4250545/9cc2f6dc-3a84-11e4-9038-8aa60d31f617.png)

**Resolution**:  Change he label to read only "Total:"

**Comment by kanglu666** [comment]
updated

**Comment by JMurk** [comment]
Confirmed complete.
