### ISSUE TITLE
OAM - SSO List - Column Header Updates

### ISSUE THREAD

**Issue by JMurk** [JMurk/DPW_and_CW_Activity_Applications#25]
In the SSOs at Location grid, please update the "Link" column headers to read 

"24-Hour Report Link" and "5-Day Report Link" respectively.

![image](https://cloud.githubusercontent.com/assets/5805454/4250729/b3fabc3e-3a86-11e4-8ac0-59e7078af04d.png)

**Comment by kanglu666** [comment]
updated

**Comment by JMurk** [comment]
I still see the columns labeled as "Link"

![image](https://cloud.githubusercontent.com/assets/5805454/4323591/c4a64362-3f51-11e4-82ad-41314ef051b1.png)

**Comment by kanglu666** [comment]
updated

**Comment by JMurk** [comment]
Confirmed complete.
