### ISSUE TITLE
OAM - Zoom to SSO 

### ISSUE THREAD

**Issue by JMurk** [JMurk/DPW_and_CW_Activity_Applications#26]
Please add a Zoom To function to the SSO tab.  The user should be able to select and SSO from the grid and zoom to the point in the map.

![image](https://cloud.githubusercontent.com/assets/5805454/4250752/f131cd36-3a86-11e4-8768-47c2cd0420cd.png)

**Comment by kanglu666** [comment]
zoom in to selected sso function has been finished. please test.
Just saw that, there are some bad location SSO features in dev.

**Comment by JMurk** [comment]
Confirmed complete.  Will check bad geometry.

**Comment by JMurk** [comment]
Reopening, please add to the SSOs to Investigate list.

**Comment by kanglu666** [comment]
done at city dev

**Comment by JMurk** [comment]
Confirmed complete on dev, please push to prod.

**Comment by kanglu666** [comment]
done

**Comment by JMurk** [comment]
Confirmed complete.
