### ISSUE TITLE
OAM - Recommendation - Autopopulate Recommended By

### ISSUE THREAD

**Issue by JMurk** [JMurk/DPW_and_CW_Activity_Applications#27]
Please auto populate the Recommended By field with the FULL NAME of the logged in user.  This should be for inserts only.

![image](https://cloud.githubusercontent.com/assets/5805454/4250862/03c0a4da-3a88-11e4-8ec7-eeae66727c03.png)

**Comment by kanglu666** [comment]
updated. need further enhancement after we plug in this app to the admin portal

**Comment by JMurk** [comment]
Confirmed complete.  We should populate with Full name once hooked up into security.
