### ISSUE TITLE
OAM - Recommendation - Rec Folder Path Label

### ISSUE THREAD

**Issue by JMurk** [JMurk/DPW_and_CW_Activity_Applications#28]
Please update the "Rec. Folder" label to read "Recommendation Folder Path:"

![image](https://cloud.githubusercontent.com/assets/5805454/4250901/679e3c42-3a88-11e4-9901-4d85d5a9d02a.png)

**Comment by kanglu666** [comment]
updated

**Comment by JMurk** [comment]
You have to colons in there, please delete one.

![image](https://cloud.githubusercontent.com/assets/5805454/4324158/877af87e-3f57-11e4-90f9-8713192e79a2.png)

**Comment by kanglu666** [comment]
updated

**Comment by JMurk** [comment]
Confirmed complete.
