### ISSUE TITLE
OAM - Recommendation -Review Date Label Adjustment

### ISSUE THREAD

**Issue by JMurk** [JMurk/DPW_and_CW_Activity_Applications#29]
**Issue**:  The Review Date label on the recommendation form is too close to the text box to its left.

![image](https://cloud.githubusercontent.com/assets/5805454/4251015/6a0944d0-3a89-11e4-80a2-eaaa6fc67cb1.png)

**Resolution**:  Align the label with the Review Date text box

**Comment by kanglu666** [comment]
updated

**Comment by JMurk** [comment]
Confirmed complete.
