### ISSUE TITLE
OAM - Build in Security

### ISSUE THREAD

**Issue by JMurk** [JMurk/DPW_and_CW_Activity_Applications#31]
Please add security to this application.  It should be added to the admin tool so that users can be managed as well.

For now, we will only have a "User" security level.

**Comment by kanglu666** [comment]
windows login check build in.
Need work with Jessey to plug in to this app to the admin portal

**Comment by JMurk** [comment]
Please coordinate with Jesse.

**Comment by kanglu666** [comment]
Joe, please add Jesse to this repository.
Jessey, please add the OAM app to portal. 
it should be like the Desltop Utility Viewer, all city login can access it.

**Comment by JMurk** [comment]
Jesse - There will only be one security level for this app called "User" (much like Leak Detection App)

**Comment by jday3** [comment]
This is resolved locally and I will push to prod tomorrow morning

**Comment by jday3** [comment]
This is now on dpwview. OAM security is listed under the mobile apps (although its not a mobile app, it was easier to put there than under utility viewer)

**Comment by JMurk** [comment]
Please push to dev as well, if possible.

**Comment by jday3** [comment]
It's on dev now

**Comment by kanglu666** [comment]
Joe, before i redirect OAM app using admin portal as the security check, please add some city users from admin portal. because once switching the new security, city user not in the OAM group will have no access to the app.

**Comment by JMurk** [comment]
Users have been added.

**Comment by kanglu666** [comment]
OAM is now using admin portal checking user. if city users are not in the OAM app group, they will be redirected back to the portal page.

**Comment by JMurk** [comment]
Confirmed complete.
