### ISSUE TITLE
OAM - Map - Hide Non Functional Buttons

### ISSUE THREAD

**Issue by JMurk** [JMurk/DPW_and_CW_Activity_Applications#32]
Please hide the buttons on he toolbar that are not functional (e.g. print, help).

![image](https://cloud.githubusercontent.com/assets/5805454/4251187/1fffffe4-3a8b-11e4-8c24-3ac7089d2919.png)

**Comment by kanglu666** [comment]
updated at dev.

**Comment by JMurk** [comment]
Confirmed complete.
