### ISSUE TITLE
OAM - Table of Contents - Label

### ISSUE THREAD

**Issue by JMurk** [JMurk/DPW_and_CW_Activity_Applications#33]
Please add an s to the end of the label so that it reads "Table of Contents"

![image](https://cloud.githubusercontent.com/assets/5805454/4322313/6d49fd7a-3f47-11e4-8af2-f90a684337eb.png)

**Comment by kanglu666** [comment]
updated

**Comment by JMurk** [comment]
Confirmed complete.
