### ISSUE TITLE
OAM - Status Details - Autopopulate User

### ISSUE THREAD

**Issue by JMurk** [JMurk/DPW_and_CW_Activity_Applications#35]
**Issue:**  The Details table is storing "Test User" as the User. It should be the name of the logged in user.

![image](https://cloud.githubusercontent.com/assets/5805454/4324250/788199e4-3f58-11e4-83f7-a5f91bb6bdb2.png)

**Resolution:** Update the autopopulate to be the currently logged in user.

**Comment by kanglu666** [comment]
done.

**Comment by JMurk** [comment]
Confirmed complete
