### ISSUE TITLE
OAM - Adjustable TOC Panel

### ISSUE THREAD

**Issue by JMurk** [JMurk/DPW_and_CW_Activity_Applications#36]
**Question:**  Is it possible to make the bottom map panel (holds TOC, results, and locator) vertically adjustable?  

Sometimes the area is so small, it is hard to see everything.  If this is manually adjustable, the user can adjust it to their liking.

![image](https://cloud.githubusercontent.com/assets/5805454/4345388/2b00074a-40cb-11e4-9809-7508c84cb935.png)

**Comment by kanglu666** [comment]
right panel (Map, TOC, results, and locator) is now vertically adjustable .

**Comment by JMurk** [comment]
Confirmed complete.
