### ISSUE TITLE
OAM - SSO Report Links Question

### ISSUE THREAD

**Issue by JMurk** [JMurk/DPW_and_CW_Activity_Applications#37]
**Question:**  Is there anyway to hide links to 24-hour and 5-day reports when there is no record for them in the SSO_HISTORY_LOG table?
![image](https://cloud.githubusercontent.com/assets/5805454/4345417/b2a7445a-40cc-11e4-9977-0dccf34eb274.png)

If not, can those link to the SSO feature class and pull the info from there?

**Comment by kanglu666** [comment]
1: no way to hide the links if there is no record in log table. 
actually, when this goes to prod, 24HR and 5DAY SSOs should have records in sso_history_table.

2: hyperlink is to the SSO report app, cant pull data fro the SSO feature class.

**Comment by JMurk** [comment]
OK, closing.
