### ISSUE TITLE
OAM - Investigation - Form Layout

### ISSUE THREAD

**Issue by JMurk** [JMurk/DPW_and_CW_Activity_Applications#39]
Please move Investigation Date and Address to the top of the form, next to Investigation ID.

![image](https://cloud.githubusercontent.com/assets/5805454/4345437/1b7df7de-40ce-11e4-8d48-f0a396b4c57b.png)

**Comment by kanglu666** [comment]
done

**Comment by JMurk** [comment]
Can you right-alight the labels so that they are close to the input box?

**Comment by kanglu666** [comment]
done

**Comment by JMurk** [comment]
Confirmed complete dev & prod.
