### ISSUE TITLE
OAM - SSOs to Review - Change Name

### ISSUE THREAD

**Issue by JMurk** [JMurk/DPW_and_CW_Activity_Applications#4]
Please change the SSOs to Review heading to read "SSOs to Investigate."  Also, update the Load SSOs to review to read "Load SSOs without and Investigation"

![image](https://cloud.githubusercontent.com/assets/5805454/4153337/b4fae184-3457-11e4-9ecc-e5a5d43ca1ce.png)

![image](https://cloud.githubusercontent.com/assets/5805454/4153340/b9aa2c44-3457-11e4-8acc-70f7241eeb44.png)

**Comment by kanglu666** [comment]
updated

**Comment by JMurk** [comment]
Shoot, I had a typo above.  It should be "an Investigation" not "and Investigation."  Please update.

**Comment by kanglu666** [comment]
updated

**Comment by JMurk** [comment]
Confirmed complete.
