### ISSUE TITLE
OAM - Data Issue - LAST_OCCURRENCE_DATE

### ISSUE THREAD

**Issue by JMurk** [JMurk/DPW_and_CW_Activity_Applications#40]
**Issue:**  The field Most Recent Occurrence in the app should actually be writing to the LAST_OCCURRENCE_DATE field in the table.

![image](https://cloud.githubusercontent.com/assets/5805454/4345456/8aca00a0-40cf-11e4-8109-b27ba5c83803.png)

**Comment by kanglu666** [comment]
should be fixed, please test

**Comment by JMurk** [comment]
Confirmed complete.
