### ISSUE TITLE
OAM - Data Issue - Cause Toggles

### ISSUE THREAD

**Issue by JMurk** [JMurk/DPW_and_CW_Activity_Applications#41]
**Issue:**  When a user leaves a checkbox untoggled, the database leaves the corresponding field in the database null.

![image](https://cloud.githubusercontent.com/assets/5805454/4345464/09e11a36-40d0-11e4-8f96-1a60cde8c0c1.png)

**Resolution:**  Please update so that blank checkboxes write 0 (No) to the table.

**Comment by kanglu666** [comment]
updated

**Comment by JMurk** [comment]
Confirmed complete.
