### ISSUE TITLE
OAM - Recommendations - Change Recommendation Type Values

### ISSUE THREAD

**Issue by JMurk** [JMurk/DPW_and_CW_Activity_Applications#43]
Please update the Recommendation drop down
![image](https://cloud.githubusercontent.com/assets/5805454/4426497/70aa3fd4-45b4-11e4-9d8b-032845036d9c.png)

To use the following codes and descriptions:
![image](https://cloud.githubusercontent.com/assets/5805454/4426542/e8f3d02c-45b4-11e4-9be2-21a95d325063.png)

**Comment by kanglu666** [comment]
updated in dev, please test

**Comment by JMurk** [comment]
Confirmed complete in dev, ready for push to prod.

**Comment by kanglu666** [comment]
updated in prod

**Comment by JMurk** [comment]
Confirmed complete.
