### ISSUE TITLE
OAM - Investigations - Add SR and WO Links to SSO List in Investigation

### ISSUE THREAD

**Issue by JMurk** [JMurk/DPW_and_CW_Activity_Applications#46]
Please add the Work Order ID and Service Request ID columns from to "SSOs to Investigate" list
![image](https://cloud.githubusercontent.com/assets/5805454/4532150/46ca326c-4d90-11e4-94ad-ef6672eadf28.png)

 to the SSO list within the SSO Tab of the Investigation.
![image](https://cloud.githubusercontent.com/assets/5805454/4532155/53f99a68-4d90-11e4-8114-c0d2c372281c.png)

Make sure that they are hyperlinked.

**Comment by kanglu666** [comment]
done on dev

**Comment by JMurk** [comment]
Confirmed complete on dev, push to prod

**Comment by kanglu666** [comment]
updated at PROD

**Comment by JMurk** [comment]
Confirmed complete.
