### ISSUE TITLE
OAM - SSO Investigation - Date

### ISSUE THREAD

**Issue by JMurk** [JMurk/DPW_and_CW_Activity_Applications#47]
**Issue:**  The app displays SSO date & time, however only date is needed.

![image](https://cloud.githubusercontent.com/assets/5805454/4592424/68868390-507b-11e4-9127-633eb4b34df7.png)

**Resolution:**  Please update to only show DATE and not time.  This should be done in the SSOs to investigate list and the SSOs at Location list.

**Comment by kanglu666** [comment]
done on dev

**Comment by JMurk** [comment]
Confirmed complete in dev, push to prod

**Comment by kanglu666** [comment]
updated at PROD

**Comment by JMurk** [comment]
confirmed complete.
