### ISSUE TITLE
OAM - SSOs Investigation - Add Recent SSO List

### ISSUE THREAD

**Issue by JMurk** [JMurk/DPW_and_CW_Activity_Applications#48]
Please add a button to the left of the Load SSOs without an Investigation button entitled "Load Recent SSOs with an Investigation"

-When a user clicks this button, the system will load a table of SSOs that occurred in the past 30 days and have an InvestigationID.

-The table should have columns for SSOID, Date, Address, SR Number (linked), WO Number (linked), Overflow Type, Choke Type, and Investigation ID.

-The Investigation ID should be linked.  When clicking the link, the system will open the investigation details.

**Comment by kanglu666** [comment]
new function has been added at city dev, please test

**Comment by JMurk** [comment]
Please capitalize Reviewed here : 
![image](https://cloud.githubusercontent.com/assets/5805454/4811037/a6e550c2-5eb7-11e4-94d8-b76af2f8bfa1.png)

Everything else looks good

**Comment by JMurk** [comment]
This has changed... closing this issue.
