### ISSUE TITLE
OAM - Sort Lists

### ISSUE THREAD

**Issue by JMurk** [JMurk/DPW_and_CW_Activity_Applications#49]
Please sort lists in the application as follows:

SSOs to Investigation - By Date, Oldest to Newest
Investigations - By Investigation Date, Newest to Oldest
SSOs at Location - By Date, Newest to Oldest
Existing Recommendations - By Date, Newest to Oldest

**Comment by kanglu666** [comment]
done on dev

**Comment by JMurk** [comment]
Confirmed complete in dev, push to prod.

**Comment by kanglu666** [comment]
updated at PROD

**Comment by JMurk** [comment]
confirmed complete.
