### ISSUE TITLE
OAM - Add to Existing Investigation - Message Change

### ISSUE THREAD

**Issue by JMurk** [JMurk/DPW_and_CW_Activity_Applications#5]
Please change the following message:

![image](https://cloud.githubusercontent.com/assets/5805454/4153394/5d5961e8-3458-11e4-81bb-fbb5aecd64bf.png)

to read:

"Selected SSOs have been successfully assigned to the existing investigation!"

**Comment by kanglu666** [comment]
done

**Comment by JMurk** [comment]
Confirmed complete.
