### ISSUE TITLE
OAM - New SSO Map Service

### ISSUE THREAD

**Issue by JMurk** [JMurk/DPW_and_CW_Activity_Applications#50]
In the Map, please re-point the SSO layer to the SSO_Investigations Map service.

**Comment by kanglu666** [comment]
i dont see the new sso_investigations map service

**Comment by JMurk** [comment]
sso_investigation is on dev.  Please implement there first.

**Comment by jday3** [comment]
Complete on dev

**Comment by JMurk** [comment]
Confirmed complete on dev, please push to prod.

**Comment by jday3** [comment]
on 10.2 prod

**Comment by jday3** [comment]
All other issues completed before are on prod

**Comment by JMurk** [comment]
Complete.
