### ISSUE TITLE
OAM - Recent SSOs with Investigation List - Add Repeat Column

### ISSUE THREAD

**Issue by JMurk** [JMurk/DPW_and_CW_Activity_Applications#51]
Please add a column in the "Recently Reviewed SSOs" list called "Repeats."  It should be placed to the right on Investigation ID.

The column should query a count on Investigation ID in the SSO feature class.  So, if the Investigation ID is 2400 and 4 records have that value, the Repeats column will read 4 for all of those records.

**Comment by kanglu666** [comment]
all query data are coming from map services, cant add a calculated field "repeat".

**Comment by JMurk** [comment]
I added a field called REPEATS to the "Investigated SSOs" layer in the SSO_Investigation map service on dev.

**Comment by jday3** [comment]
Complete on dev

**Comment by JMurk** [comment]
Confirmed complete on dev, please push to prod.

**Comment by JMurk** [comment]
The column isn't populating.  I had to make some changes to the map service, but after doing so, all SSO should have a value populated in that column.

![image](https://cloud.githubusercontent.com/assets/5805454/5507312/0d403130-8770-11e4-856b-46a6ad764969.png)

**Comment by jday3** [comment]
Fixed on production

**Comment by JMurk** [comment]
Confirmed complete.
