### ISSUE TITLE
OAM - SSO Investigation - Load ALL SSOs

### ISSUE THREAD

**Issue by JMurk** [JMurk/DPW_and_CW_Activity_Applications#52]
Please changes the Recently Reviewed list to load ALL SSOs where INVESTIGATIONID is not null.

The list name should be changed to "All Investigated SSOs"
![image](https://cloud.githubusercontent.com/assets/5805454/4846964/5b1244d6-604f-11e4-9909-dba4cc4a5f74.png)

The button should be changed to read "Load All Investigated SSOs"
![image](https://cloud.githubusercontent.com/assets/5805454/4846981/7b2903b8-604f-11e4-8d2b-2f03a9455572.png)

**Comment by kanglu666** [comment]
updated

**Comment by JMurk** [comment]
Confirmed complete.
