### ISSUE TITLE
OAM - SSOs to Investigate - Default Order Change

### ISSUE THREAD

**Issue by JMurk** [JMurk/DPW_and_CW_Activity_Applications#53]
Please updated the SSOs to Investigate list so that it is ordered from oldest to newest by default.

![image](https://cloud.githubusercontent.com/assets/5805454/4980834/8d4b18e4-6903-11e4-948c-8a8d98454901.png)

**Comment by jday3** [comment]
Done, on dev

**Comment by JMurk** [comment]
Confirmed complete on dev, please push to prod.

**Comment by JMurk** [comment]
Complete.
