### ISSUE TITLE
OAM - SSO Investigation - Date Problems

### ISSUE THREAD

**Issue by JMurk** [JMurk/DPW_and_CW_Activity_Applications#54]
**Issue:**: When creating a new investigation, the Investigation Date auto-populates with an SSO Date.  Alos, the system prevents the user from selecting and saving today's date.

**Resolution:**  For new investigations, please auto-populate the Investigation date with the SYSTEM date.  Also, please revise the validation check so that it is <= system date.

**Comment by jday3** [comment]
Done, on dev

**Comment by JMurk** [comment]
Confirmed complete, please push to prod.

**Comment by JMurk** [comment]
Complete.
