### ISSUE TITLE
OAM - SSO Investigation - Add Column (Choke Feature Type)

### ISSUE THREAD

**Issue by JMurk** [JMurk/DPW_and_CW_Activity_Applications#55]
Please add a column to the SSOs to Investigate list between Address and SR Number called "Choke Type".  It should pull the field CHOKE_TYPE field in the SSO feature class.

![image](https://cloud.githubusercontent.com/assets/5805454/5207214/3c3a43ec-7576-11e4-9c63-2b389e7f6e1e.png)

**Comment by jday3** [comment]
Done on dev

**Comment by JMurk** [comment]
Confirmed complete in dev, please push to prod.

**Comment by JMurk** [comment]
Complete.
