### ISSUE TITLE
OAM - SSO Investigation - Choke Feature Type Value

### ISSUE THREAD

**Issue by JMurk** [JMurk/DPW_and_CW_Activity_Applications#56]
Please add "None" and "N/A" as values to the "Choked Feature" dropdown in the investigation form.

![image](https://cloud.githubusercontent.com/assets/5805454/5365913/88f7ce60-7fbd-11e4-8644-b33ff6710aab.png)

The codes are NON for None and NA for N/A

**Comment by jday3** [comment]
Done on dev, but are those codes in the domain?

**Comment by JMurk** [comment]
Yes they are in the domain in both dev and prod.  Please push to prod.

**Comment by JMurk** [comment]
Complete
