### ISSUE TITLE
OAM - SSO Investigation - Select Choked Feature ID from the Map

### ISSUE THREAD

**Issue by JMurk** [JMurk/DPW_and_CW_Activity_Applications#57]
**Enhancement:**  Users would like the ability to populate the choked feature ID field by selecting a feature on the map.

![image](https://cloud.githubusercontent.com/assets/5805454/5495347/caec0d7c-86ca-11e4-9d31-ee62f395ff9e.png)

I'm not sure what the best way to implement this would be from a development standpoint, so let me know your thoughts.

**Comment by jday3** [comment]
I implemented a drag and drop solution: The user identifies the feature on the map, then drags the feature from the results tree and drops into the 'Choked Feature ID' text field. Then, the Choked feature type and ID are populated.
![draganddrop](https://cloud.githubusercontent.com/assets/4439618/5558561/80b8c03e-8cfa-11e4-9721-7a793a2f1ca9.gif)

**Comment by jday3** [comment]
This is on dev for you to test

**Comment by JMurk** [comment]
Looks good, please push to prod.

**Comment by jday3** [comment]
Done

**Comment by JMurk** [comment]
Confirmed complete.

**Comment by JMurk** [comment]
They have requested that this functionality be put in place for the Overflowing feature ID as well.  Please implement if possible.

**Comment by jday3** [comment]
Done on dev

**Comment by jday3** [comment]
Double check that I'm allowing the correct layers to be used for the overflowing feature

**Comment by JMurk** [comment]
Add:
Force Mains (corresponds with Broken Pipe)
Lateral/CO Points (corresponds with Clean Out/ OVERFLOWING_POINT_ID)

Also check that you have Lampholes set (couldn't find one on the map to test).

**Comment by jday3** [comment]
I added those two layers and checked that lamphole works

**Comment by JMurk** [comment]
Please push to prod.

**Comment by jday3** [comment]
Done

**Comment by JMurk** [comment]
Confirmed complete.
