### ISSUE TITLE
DAM- SSO Investigations - Load Lists Initially

### ISSUE THREAD

**Issue by JMurk** [JMurk/DPW_and_CW_Activity_Applications#58]
**Issue:** Upon selecting the SSO Investigations activity, the Lists are no loaded.

![image](https://cloud.githubusercontent.com/assets/5805454/5505725/8433cdd8-8761-11e4-9f88-ec023702c233.png)

**Resolution:**  Please load both lists upon initial log in.

**Comment by jday3** [comment]
Done, on prod and dev

**Comment by jday3** [comment]
Also, the list of SSOs in an investigation should update properly when creating a new investigation

**Comment by JMurk** [comment]
Confirmed complete.
