### ISSUE TITLE
OAM - SSO Investigation - Add Value for Followup Status

### ISSUE THREAD

**Issue by JMurk** [JMurk/DPW_and_CW_Activity_Applications#59]
Please add the value of "Private" (code: PRI in the domain) to the Follow-Up Status dropdown within the investigation details page.

![image](https://cloud.githubusercontent.com/assets/5805454/5782157/f00a887c-9d86-11e4-865f-2182c522dc5d.png)

**Comment by jday3** [comment]
Done on dev and prod

**Comment by JMurk** [comment]
Confirmed complete
