### ISSUE TITLE
OAM - SSO Investigation - SSO Date Off

### ISSUE THREAD

**Issue by JMurk** [JMurk/DPW_and_CW_Activity_Applications#60]
**Issue:**  In the SSOs grid within an investigation, the date is displaying 1 day before the actual date stored in the database.

In this example, the dates should be 1/15/15 and 12/2/14
![image](https://cloud.githubusercontent.com/assets/5805454/5786540/024970d8-9db5-11e4-9e2d-fbb180c86a41.png)

**Resolution:**  Please investigate and resolve accordingly.

**Comment by jday3** [comment]
I had the dates offset by 4 hours where they needed to be offset by 5 hours since eastern time is -5 hours to GMT. Fixed on prod

**Comment by JMurk** [comment]
Confirmed complete.
