### ISSUE TITLE
OAM - SSO Investigation - Overflowing Feature & ID Not Auto-Populating

### ISSUE THREAD

**Issue by JMurk** [JMurk/DPW_and_CW_Activity_Applications#61]
**Issue:**  When creating a new investigation from a selected SSO, the Overflowing Feature and Overflowing Feature ID are failing to populate.

![image](https://cloud.githubusercontent.com/assets/5805454/5823952/e25c1756-a0ae-11e4-9b2f-6d8f836d026b.png)

**Resolution:** Please investigate and resolve accordingly.

**Comment by jday3** [comment]
Fixed on dev

**Comment by JMurk** [comment]
Confirmed complete on dev, please push to prod.

**Comment by jday3** [comment]
Fixed the issue where when OVFL_STRUCTURE='CO', the overflow id was pulled from OVERFLOW_POINT_ID instead of OVERFLOW_TAG. This was pushed to dev and prod.

**Comment by JMurk** [comment]
Confirmed complete.
