### ISSUE TITLE
OAM - SSO Investigation - Calendar Control Issues

### ISSUE THREAD

**Issue by JMurk** [JMurk/DPW_and_CW_Activity_Applications#62]
**Issue:** The calandar controls used by the activity manager allow users to pick the date, but also the month and the year.  The month and the year controls do not result in any change:
![image](https://cloud.githubusercontent.com/assets/5805454/5824700/2696df46-a0b4-11e4-87bc-9d4924d07061.png)

**Resolution:** Fix that part of the control so it works, otherwise remove/disable it.

**Comment by jday3** [comment]
Related to BUG - EXTJS-15968  [Ext JS 5.1 Release Notes](http://docs.sencha.com/extjs/5.1/whats_new/release_notes.html)

**Comment by jday3** [comment]
I'm going to upgrade this app from 5.0 to 5.1 to take advantage of this bug fix.

**Comment by jday3** [comment]
The app is upgraded on dev, so now the month/year dropdown should work. There is no simple way to hide the dropdown.

**Comment by JMurk** [comment]
Confirmed complete on dev.  If the change was simple, push to prod (off hours, if possible)

**Comment by jday3** [comment]
pushed to prod

**Comment by JMurk** [comment]
Confirmed complete.
