### ISSUE TITLE
OAM - SSO Investigation - Save Changes Prompt

### ISSUE THREAD

**Issue by JMurk** [JMurk/DPW_and_CW_Activity_Applications#63]
**Issue:**  The Save Changes modal screen is prompted every time a user chooses to leave an editable screen regardless of if there are unsaved changes or not.
![image](https://cloud.githubusercontent.com/assets/5805454/5840479/e9f94122-a163-11e4-9658-ba4ac3d45ff2.png)

**Resolution:**  Please adjust so this message only appears when there are pending, unsaved changes in the form they are leaving.

**Comment by jday3** [comment]
This should be fixed, on dev

**Comment by JMurk** [comment]
This is still appearing when there are no pending changes.

**Comment by taojun545** [comment]
Updated on dev. I also fixed the Alert Prompt on CCTV Review. If there are pending, unsaved changes in the CCTV Review form, it will be shown when they are leaving.

**Comment by JMurk** [comment]
Confirmed complete on dev, ready for prod.

**Comment by taojun545** [comment]
Updated on production.

**Comment by JMurk** [comment]
Confirmed complete.
