### ISSUE TITLE
OAM - SSO Investigation - Highlight Selected SSO

### ISSUE THREAD

**Issue by JMurk** [JMurk/DPW_and_CW_Activity_Applications#64]
Users would like an identified SSO on the map to highlight in the “SSOs to Investigate” grid.

The workflow would be:
1. Identify non-investigated SSO on the map.
2. Select the record in the Identify Results
3. The SSO row automatically center (poosible?) and highlights in the "SSOs to Investigate" grid.

![image](https://cloud.githubusercontent.com/assets/5805454/5842047/bf9f707a-a16f-11e4-87db-5f834928f808.png)

**Comment by jday3** [comment]
This works on dev

**Comment by JMurk** [comment]
I'm not seeing it highlight in the SSOs to Investigate grid.

**Comment by jday3** [comment]
It only highlights in the investigate grid when it exists in there (some aren't in the grid)

**Comment by JMurk** [comment]
Confirmed complete, please push to prod.

**Comment by jday3** [comment]
now on prod

**Comment by JMurk** [comment]
Confirmed complete.
