### ISSUE TITLE
OAM - SSO Investigation - Assigning to Existing Investigation - Autopopulate Inv. Grid

### ISSUE THREAD

**Issue by JMurk** [JMurk/DPW_and_CW_Activity_Applications#65]
When assigning SSOs to an existing investigation, auto-populate the search results grid with investigations (derived from SSO.INVESTIGATIONID) within 100' of the selected SSOs (only possible if one is selected).

![image](https://cloud.githubusercontent.com/assets/5805454/5842480/2363afb0-a173-11e4-927e-f6d42c94ed0e.png)

**Comment by jday3** [comment]
Done on dev

**Comment by JMurk** [comment]
A bit of a delay for the records load, but that's OK.  Push to prod.

**Comment by jday3** [comment]
now on prod

**Comment by JMurk** [comment]
Confirmed complete.
