### ISSUE TITLE
OAM - SSO Investigation - Remove WO Number Coumns

### ISSUE THREAD

**Issue by JMurk** [JMurk/DPW_and_CW_Activity_Applications#66]
Please Remove the WO Number columns from the "SSOs to Investigate" grid and the "Recently Reviewed SSOs" grid.  They are no longer needed by the users.

**Comment by jday3** [comment]
Done on dev

**Comment by JMurk** [comment]
Confirmed complete, please push to prod.

**Comment by jday3** [comment]
on prod

**Comment by JMurk** [comment]
Confirmed complete.
