### ISSUE TITLE
OAM - SSO Investigation - Recently Reviewed SSOs Label

### ISSUE THREAD

**Issue by JMurk** [JMurk/DPW_and_CW_Activity_Applications#67]
Please capitalize reviewed in the "Recently reviewed SSOs" label.

![image](https://cloud.githubusercontent.com/assets/5805454/5842535/9ccacb04-a173-11e4-9150-9b713c919069.png)

**Comment by jday3** [comment]
Done on dev

**Comment by JMurk** [comment]
Confirmed complete, please push to prod.

**Comment by jday3** [comment]
on prod

**Comment by JMurk** [comment]
Confirmed complete.
