### ISSUE TITLE
OAM - SSO Investigation - Zoom to SSO When Investigation Opens

### ISSUE THREAD

**Issue by JMurk** [JMurk/DPW_and_CW_Activity_Applications#68]
The Open Investigation button (i) within the Recently Investigated SSOs grid should also zoom to the SSO in the map.

![image](https://cloud.githubusercontent.com/assets/5805454/5842630/5ab123ac-a174-11e4-80f6-4e33074fa0ff.png)

**Comment by jday3** [comment]
Done, on dev

**Comment by JMurk** [comment]
Confirmed complete on dev, please push to prod.

**Comment by jday3** [comment]
on prod

**Comment by JMurk** [comment]
Confirmed complete.
