### ISSUE TITLE
OAM - SSO Investigation - Investigation Info Labels

### ISSUE THREAD

**Issue by JMurk** [JMurk/DPW_and_CW_Activity_Applications#69]
On the Investigation Details page, add Investigation ID and Address as a readable label along the top so that users do not have to change tabs to see that information.

![image](https://cloud.githubusercontent.com/assets/5805454/5842819/0da664f8-a176-11e4-9777-28959d300169.png)

**Comment by jday3** [comment]
Done, on dev

**Comment by JMurk** [comment]
Confirmed complete, please push to prod.

**Comment by jday3** [comment]
on prod

**Comment by JMurk** [comment]
Confirmed complete.
