### ISSUE TITLE
OAM - Searching Existing Investigation - Add Date Range

### ISSUE THREAD

**Issue by JMurk** [JMurk/DPW_and_CW_Activity_Applications#7]
Please add the ability to search for investigations based on a given date range.

**Comment by kanglu666** [comment]
done

**Comment by JMurk** [comment]
Confirmed, but please update the message:

![image](https://cloud.githubusercontent.com/assets/5805454/4235585/9ec9b322-39c0-11e4-8adf-9f9cbd83d5ab.png)

To read:
"Please choose a start date and end date!"

**Comment by kanglu666** [comment]
updated

**Comment by JMurk** [comment]
Confirmed complete.
