### ISSUE TITLE
OAM - SSO Investigation - Move SSO Points

### ISSUE THREAD

**Issue by JMurk** [JMurk/DPW_and_CW_Activity_Applications#70]
Add the functionality that will allow uses to move the SSO point feature within the map.  The current SSO_Investigation service can not be a feature service because of data sources outside of the geodatabase.  Would a new service be able to be used?

**Comment by jday3** [comment]
Why do we want to allow SSOs to be moved in the investigation app? I'm not sure how we would get this to work unless we use a new service, but the SSO data for the investigations is being queried through the SSO_Investigation map service.

**Comment by JMurk** [comment]
This is something that they need to do as a part of their workflow.  I have created a feature service on dev called SSO_Investigation_Feature_Service.  You should use that for mapping, then use the SSO_Investigation map service to populate the grids.

**Comment by jday3** [comment]
Done, on dev. The following gif shows how to move an SSO. Currently, it only allows you to move Non-Investigated SSOs, but if this method is good I can add Investigated SSOs as well.

![move_sso](https://cloud.githubusercontent.com/assets/4439618/6604205/4dba2a36-c7fd-11e4-8945-8acfd1ac76f9.gif)

**Comment by JMurk** [comment]
Confirmed complete, please expand to the Investigated SSO layer and push to prod.

**Comment by jday3** [comment]
The code has been migrated to production, but the SSO_Investigation_Feature_Service feature service needs to be published in prod

**Comment by JMurk** [comment]
The feature service has been published.

**Comment by jday3** [comment]
Okay, it seems to be working

**Comment by JMurk** [comment]
Confirmed complete.
