### ISSUE TITLE
OAm - SSO Investigations - Edit INVESTIGATIONID attribute of selected SSO

### ISSUE THREAD

**Issue by JMurk** [JMurk/DPW_and_CW_Activity_Applications#71]
Users should be able to edit the INVESTIGATIONID of a selected SSO.  This should be expanded with the thought that other attributes may be added as editable in the future.

**Comment by jday3** [comment]
Where would you want to edit the investigation id? in the map results?

**Comment by JMurk** [comment]
Yeah that would work, if it's possible of course.

**Comment by jday3** [comment]
now on dev/prod

There is a collapsed grid at the bottom of the main SSO Investigations page where you can drag Investigated/Non-Investigated SSOs from the map results and then edit the records. For now, the only editable field is the Investigation ID

**Comment by JMurk** [comment]
Confirmed complete in both environments.
