### ISSUE TITLE
OAM - SSO Investigation - Add SSOs to Investigation

### ISSUE THREAD

**Issue by JMurk** [JMurk/DPW_and_CW_Activity_Applications#72]
Within the SSO tab of the Investigation details page, add a button/function that allows users to add SSOs to the investigation from the map.  Drag and drop possible?

![image](https://cloud.githubusercontent.com/assets/5805454/5843088/05f4b7bc-a178-11e4-80c6-ec37d81c27d8.png)

**Comment by jday3** [comment]
Done on dev. Non Investigated SSOs can be added from the map results by dragging and dropping on the table as shown below.

![add_sso](https://cloud.githubusercontent.com/assets/4439618/6604352/26e4b2a4-c7fe-11e4-90ed-890a95649c11.gif)

**Comment by JMurk** [comment]
Confirmed complete, please push to prod.

**Comment by jday3** [comment]
Pushed to prod

**Comment by JMurk** [comment]
Confirmed complete.
