### ISSUE TITLE
OAM - SSO Investigation - Add Attached Document Funtionality

### ISSUE THREAD

**Issue by JMurk** [JMurk/DPW_and_CW_Activity_Applications#73]
Add in the “Attached Documents” tool from the Utility Viewer.  This will allow users to view CCTV videos directly from the application.

![image](https://cloud.githubusercontent.com/assets/5805454/5843131/58e71226-a178-11e4-9520-ec1e90c2590d.png)

**Comment by jday3** [comment]
done on dev

**Comment by JMurk** [comment]
Confirmed complete.

**Comment by JMurk** [comment]
The identify isn't working.

**Comment by jday3** [comment]
What do you mean?

**Comment by JMurk** [comment]
Welp, it's working now so disregard that comment.  Please push to prod.

**Comment by jday3** [comment]
now on prod

**Comment by JMurk** [comment]
The links to the video are pointing to the ip rather than dpwview.baltimorecity.gov like in the utility viewer.  Thus links don't work outside of the city network.

**Comment by jday3** [comment]
fixed

**Comment by JMurk** [comment]
Confirmed complete.
