### ISSUE TITLE
OAM - SSO Investigation - Updates to Existing Investigations Not Saving

### ISSUE THREAD

**Issue by JMurk** [JMurk/DPW_and_CW_Activity_Applications#75]
**Issue:**  Edits made to existing investigations are not saving (prod).  They appear to save, but when returning to the record, they are gone.

![image](https://cloud.githubusercontent.com/assets/5805454/5902609/d0fb4a64-a549-11e4-82ac-2fb0097d9fda.png)

**Resolution:**  Please investigate and resolve accordingly.  Use 2371 as a test case.

**Comment by jday3** [comment]
Should be fixed

**Comment by JMurk** [comment]
"Overflowing feature" seems like it is not saving at all.

**Comment by jday3** [comment]
dev or prod?

**Comment by JMurk** [comment]
sorry, in prod.

**Comment by jday3** [comment]
Fixed now

**Comment by JMurk** [comment]
Appears to be fixed
