### ISSUE TITLE
OAM - SSO Investigation - Overflow Type Not Displaying

### ISSUE THREAD

**Issue by JMurk** [JMurk/DPW_and_CW_Activity_Applications#76]
**Issue:**  In the "Recently Reviewed SSOs" grid, there is no data being displayed in the Overflow Type columns.

![image](https://cloud.githubusercontent.com/assets/5805454/6711089/4afcbf62-cd5b-11e4-8b9b-709ac976744b.png)

**Resolution:** Please display this values in the SSO.OVERFLOW_TYPE field.

**Comment by jday3** [comment]
fixed on prod, fix will be pushed to dev after next update

**Comment by JMurk** [comment]
Confirmed complete.
