### ISSUE TITLE
OAM - SSO Investigation - SSOs To Investigate Sorting

### ISSUE THREAD

**Issue by JMurk** [JMurk/DPW_and_CW_Activity_Applications#77]
Per the user:  table should always be sorted from oldest to newest, but it only does that the first time its loaded, not after completing investigations.

After creating a new investigation and returning to the screen, this is how it sorts.
![image](https://cloud.githubusercontent.com/assets/5805454/6754283/f16c7260-cef1-11e4-96a5-1788ff5d3936.png)

**Comment by jday3** [comment]
fixed on dev/prod

**Comment by JMurk** [comment]
Confirmed complete in both environments.
