### ISSUE TITLE
OAM - SSO Investigation - Recently Reviewed SSOs

### ISSUE THREAD

**Issue by JMurk** [JMurk/DPW_and_CW_Activity_Applications#78]
Please make the list only load the SSOs from the past 30 days in the list.  Also, the list diplays somewhere in the middle by default.  Please make sure it displays at the top.

![image](https://cloud.githubusercontent.com/assets/5805454/6754399/a8bc9fee-cef2-11e4-9585-761234066b93.png)

**Comment by jday3** [comment]
Fixed on dev/prod

**Comment by JMurk** [comment]
Confirmed complete in both environments
