### ISSUE TITLE
OAM - SSO Investigation - Add Choke Feature Value

### ISSUE THREAD

**Issue by JMurk** [JMurk/DPW_and_CW_Activity_Applications#79]
Please add Manhole (Code MH) to the Choked Feature list within the Investigation details page.

![image](https://cloud.githubusercontent.com/assets/5805454/6802832/cbfc0e3a-d209-11e4-9a29-5791fdc645fd.png)

**Comment by jday3** [comment]
done on dev

**Comment by JMurk** [comment]
Confirmed complete, please push to prod.

**Comment by jday3** [comment]
done

**Comment by JMurk** [comment]
Confirmed complete.
