### ISSUE TITLE
OAM - Searching Existing Investigation - Change Title

### ISSUE THREAD

**Issue by JMurk** [JMurk/DPW_and_CW_Activity_Applications#8]
Please change the title of this page from:

![image](https://cloud.githubusercontent.com/assets/5805454/4153546/0ace1eda-345a-11e4-9b6c-a0db56bebe41.png)

to "Update Existing Investigation"

**Comment by kanglu666** [comment]
done

**Comment by JMurk** [comment]
Confirmed complete.
