### ISSUE TITLE
OAM - SSO Investigation - Remove SSO From Edit List

### ISSUE THREAD

**Issue by JMurk** [JMurk/DPW_and_CW_Activity_Applications#80]
**Issue:**  Once you add an SSO to the editiable workspace, there is no way to remove it.  

![image](https://cloud.githubusercontent.com/assets/5805454/6972801/2f23c736-d954-11e4-9267-034f2681e4e7.png)

**Resolution:**  Please add a clear button to the individual SSO records in the list so the can be removed by the user when they have completed their edits.

**Comment by jday3** [comment]
Done on dev - there is a clear button on top of the grid

**Comment by JMurk** [comment]
Looks good but as we discussed, please add a clear button to the "Action" column so that individual records can be cleared.

**Comment by jday3** [comment]
done on dev

**Comment by JMurk** [comment]
Confirmed complete, please push to prod.

**Comment by jday3** [comment]
done

**Comment by JMurk** [comment]
Confirmed complete.
