### ISSUE TITLE
OAM - SSO Investigation - Add Other Sewer MHs to Drag and Drop

### ISSUE THREAD

**Issue by JMurk** [JMurk/DPW_and_CW_Activity_Applications#81]
Please add features identified in the "Other Sewer Manholes" layer to the drag-and-drop functionality to the Overflowing Feature ID field in the Investigation form.

![image](https://cloud.githubusercontent.com/assets/5805454/7255913/5c4e7772-e81a-11e4-8ff8-39d6833c7805.png)

**Comment by jday3** [comment]
Done on dev

**Comment by JMurk** [comment]
Confirmed complete in dev and prod.
