### ISSUE TITLE
OAM - BaseMap Displaying Over Other Layers

### ISSUE THREAD

**Issue by JMurk** [JMurk/DPW_and_CW_Activity_Applications#82]
**Issue**:  The BaseMap layer in the Activity Manager appears to be on top of all layers and does not turn off with the BaseMap toggle in the TOC.

![image](https://cloud.githubusercontent.com/assets/5805454/7937471/35cd0b4e-090e-11e5-8f96-447c29d2d55c.png)

**Resolution**: Please investigate and resolve accordingly.

**Comment by jday3** [comment]
Weird, but I am not seeing this anymore

**Comment by JMurk** [comment]
Must have been something strange going on that day.  Probably with the network. Closing.
