### ISSUE TITLE
OAM - Lookup - Date Formats

### ISSUE THREAD

**Issue by JMurk** [JMurk/DPW_and_CW_Activity_Applications#83]
**Issue:**  The date formats are a little cluttered.  Can we change the format?  Ideally it would be:

MM/DD/YYYY HH:MM (7/21/2015 01:45)

![image](https://cloud.githubusercontent.com/assets/5805454/8807347/f4a23e42-2fa9-11e5-9c5b-16f6bc4b117b.png)

**Comment by jday3** [comment]
done

**Comment by JMurk** [comment]
Confirmed complete.
