### ISSUE TITLE
OAM - Lookup - CSR ID Search Needs Wildcard

### ISSUE THREAD

**Issue by JMurk** [JMurk/DPW_and_CW_Activity_Applications#84]
**Issue:**  For the CSR ID and Address search, please add the ability to use a wild card to search.  Preferably % would be the wildcard symbol. 

![image](https://cloud.githubusercontent.com/assets/5805454/8807451/abfec006-2faa-11e5-810f-f2e501d92f2c.png)

![image](https://cloud.githubusercontent.com/assets/5805454/8807715/5da7bde8-2fac-11e5-9705-320033ac9073.png)

**Comment by jday3** [comment]
done

**Comment by JMurk** [comment]
Can you implement this for the Work Order address as well?

**Comment by jday3** [comment]
done

**Comment by JMurk** [comment]
Confirmed complete.
