### ISSUE TITLE
OAM - Lookup - Distinguish Field Labels

### ISSUE THREAD

**Issue by JMurk** [JMurk/DPW_and_CW_Activity_Applications#85]
**Issue:**  I think that the field labels need to be more distinguished from the data. 

![image](https://cloud.githubusercontent.com/assets/5805454/8808279/9dc25d18-2faf-11e5-8acd-c93cfb76d685.png)

**Resolution:**  Maybe make them bold?  Or put a box around the data?  Try whatever you think is best.

**Comment by jday3** [comment]
done

**Comment by JMurk** [comment]
Looks good.  Can you also Bold the labels in the search panel (Search By: and Search:).  Also, I think all labels should be right-aligned.  Like Address and Status.

**Comment by jday3** [comment]
done

**Comment by JMurk** [comment]
Confirmed complete.
