### ISSUE TITLE
OAM -  CW Lookup - More Wild Cards

### ISSUE THREAD

**Issue by JMurk** [JMurk/DPW_and_CW_Activity_Applications#86]
**Issue:** Amy would like users to have the ability to add wild cards to the house number so that results are returned for a specific block.  

For example:  "2% N FULTON%" would return:

-264 N FULTON AVE
-2331 N FULTON ST
-21 N FULTON AV

![image](https://cloud.githubusercontent.com/assets/5805454/9308810/1e57957c-44d4-11e5-947d-6f22bff72ed4.png)

Is this possible?  Or perhaps there is a better way for doing this?

**Comment by JMurk** [comment]
Per Amy, this is a critical item.  Please prioritize.

**Comment by jday3** [comment]
This was completed

**Comment by JMurk** [comment]
Completed
