### ISSUE TITLE
OAM - CW Lookup - Hyperlink ID in Grid

### ISSUE THREAD

**Issue by JMurk** [JMurk/DPW_and_CW_Activity_Applications#89]
In the related Work Orders grid (on both SR ans WO pages), please hyperlink the IDs to Cityworks.

![image](https://cloud.githubusercontent.com/assets/5805454/9309595/bb79ba20-44d8-11e5-9a44-36971e96cfb7.png)

**Comment by JMurk** [comment]
Seems to be in place on the Work Order page, but no the Service Request Page.

![image](https://cloud.githubusercontent.com/assets/5805454/9358131/84b8793c-4658-11e5-943b-382f190f06ba.png)

**Comment by jday3** [comment]
This is now working

**Comment by JMurk** [comment]
Complete on Cityworks Activity Browser app.
