### ISSUE TITLE
OAM - SSO Investigation Details - Owner Dropdown

### ISSUE THREAD

**Issue by JMurk** [JMurk/DPW_and_CW_Activity_Applications#9]
Please remove the valid values for the 'Owner' dropdown as they are not valid.  I will get a list of valid values from the stakeholders that we can plug in.

![image](https://cloud.githubusercontent.com/assets/5805454/4153795/3ebcd176-345c-11e4-9656-9e9ae5429621.png)

**Comment by kanglu666** [comment]
please provide the owner list

**Comment by JMurk** [comment]
![image](https://cloud.githubusercontent.com/assets/5805454/4235803/b9a8058e-39c2-11e4-8985-44bf9c6cb4de.png)

**Comment by kanglu666** [comment]
owner domain applied

**Comment by JMurk** [comment]
Confirmed complete.
