### ISSUE TITLE
OAM - CW Lookup - Back Function

### ISSUE THREAD

**Issue by JMurk** [JMurk/DPW_and_CW_Activity_Applications#91]
Per Amy:  "Is there a “back” function, like you are looking at one SR and would like to look at the previous one you had up?  Or in the Search control could see your previous searches? "

This is fairly vague, so let me know what the options are, if any.

**Comment by jday3** [comment]
This is functional on the mobile/tablet version, but not the desktop version. I could redesign the desktop version to allow this if we want to.

**Comment by JMurk** [comment]
Lets leave it as-is for now.
