### ISSUE TITLE
OAM - Not Loading on iPads/Safari

### ISSUE THREAD

**Issue by JMurk** [JMurk/DPW_and_CW_Activity_Applications#95]
**Issue:**  The application gets stuck on the loading screen when trying to access on an iPad.  This could be an issue with Safari.

Please investigate and resolve accordingly.

**Comment by jday3** [comment]
The app does load on Chrome for iOS, but the touch events don't work properly therefore making the app unusable. I don't think it will be feasible to make the OAM application compatible with iOS devices. I think it would make more sense to make iOS compatibility a requirement for the standalone cityworks app, which will be upgraded to ExtJS 6.

**Comment by jday3** [comment]
I assume that this is no longer relevant since the cityworks portion has been moved to its own application?

**Comment by JMurk** [comment]
Correct, confirmed complete.
