### ISSUE TITLE
Cityworks Activity Browser - Permissions

### ISSUE THREAD

**Issue by jday3** [JMurk/DPW_and_CW_Activity_Applications#97]
Permissions have been implemented in the cityworks app similar to the activity manager. The administration portal has been updated to allow for the adding/removal of permissions. Currently there is only one permission (Reports) and the searching functionality is available to everyone.

**Comment by JMurk** [comment]
Confirmed complete.  Ready for prod after migration.

**Comment by jday3** [comment]
now added to prod. Need icon and description though. Permissions should work
