### ISSUE TITLE
OAM - Map - Add Measure Tool

### ISSUE THREAD

**Issue by JMurk** [JMurk/DPW_and_CW_Activity_Applications#99]
Users have requested the addition of the measuring tool from the Utility Viewer in the mapping tools.

![image](https://cloud.githubusercontent.com/assets/5805454/9795583/85e3b22c-57bf-11e5-9fb0-28c0716f8c93.png)

**Comment by jday3** [comment]
done on dev

**Comment by JMurk** [comment]
The point measure tool should return State Plane coordinates and Baltimore City Grid coordinates.  This exists in the Utility Viewer.

![image](https://cloud.githubusercontent.com/assets/5805454/9905517/6fb3af32-5c53-11e5-842d-862b5e9885e9.png)

**Comment by taojun545** [comment]
Upgrade ArcGIS API from 3.10 to 3.16, and update the Measure Tool on dev.

We may need to test Map functions since the ArcGIS API Upgrade.

Thanks.

**Comment by JMurk** [comment]
Confirmed complete, ready for prod.  All other map functions appear to be working.

**Comment by taojun545** [comment]
Updated on production.

**Comment by JMurk** [comment]
Confirmed complete.
